export type Disciplina = {
  
  periodo: number;
  codigo: string;
  nome: string;
  cargaHoraria: number;
  preRequisito: string;
  universidade: string;
  tipo: "Obrigatória" | "Optativa Matemática" | "Optativa Pedagógica" | "Atividade Complementar";
  provaPresencial: boolean;
  selecionado: boolean;
  grupo?: string;
  diaDaSemana?: 'sábado'|'domingo';
  horario?: 'manhã (9:30 até 12:00)'|'tarde (13:30 até 16:00)';
  indicadorPeriodo: number;
  habilitado: boolean;
  materiasParaHabilitar?: string[]
};

export const listaDisciplinas:Disciplina[] = [
  // 1º Período
  { 
     periodo: 1,
     codigo: "EAD01038",
     nome: "Matemática Básica",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: true,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: true,  
  },
  { 
     periodo: 1,
     codigo: "EAD03046",
     nome: "Português Instrumental I",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UNIRIO",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: true,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: true,  
  },
  { 
     periodo: 1,
     codigo: "EAD01060",
     nome: "Seminários de Educação a Distância",
     cargaHoraria: 60,
     preRequisito: "não tem",
     selecionado: true,
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: true,   
  },
  { 
     periodo: 1,
     codigo: "EAD01004",
     nome: "Introdução à Informática",
     cargaHoraria: 75,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: true,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: true,  
  },
  { 
     periodo: 1,
     codigo: "EAD01072",
     nome: "Atividades Complementares I",
     cargaHoraria: 60,
     preRequisito: "não tem",
     selecionado: false,
     universidade: "UFF/UNIRIO",
     tipo: "Atividade Complementar",
     provaPresencial: false ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 2º Período
  { 
     periodo: 2,
     codigo: "EAD01082",
     nome: "Pré-Cálculo",
     cargaHoraria: 60,
     preRequisito: "Matemática Básica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,
       
  },
  { 
     periodo: 2,
     codigo: "EAD01062",
     nome: "Geometria Plana",
     cargaHoraria: 60,
     preRequisito: "Matemática Básica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 2,
     codigo: "EAD00211",
     nome: "Prática de Ensino I - Didática",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 2,
     codigo: "EAD00201",
     nome: "Fundamentos da Educação I",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo:"G2",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 3º Período
  { 
     periodo: 3,
     codigo: "EAD01083",
     nome: "Cálculo I",
     cargaHoraria: 60,
     preRequisito: "Pré-Cálculo",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 3,
     codigo: "EAD01087",
     nome: "Geometria Analítica",
     cargaHoraria: 60,
     preRequisito: "Geometria Plana",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 3,
     codigo: "EAD01063",
     nome: "Geometria Espacial",
     cargaHoraria: 60,
     preRequisito: "Geometria Plana",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 3,
     codigo: "EAD01039",
     nome: "Matemática Financeira",
     cargaHoraria: 60,
     preRequisito: "Matemática Básica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 3,
     codigo: "EAD00202",
     nome: "Fundamentos da Educação II",
     cargaHoraria: 60,
     preRequisito: "Fundamentos da Educação I",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,    
  },

  // 4º Período
  { 
     periodo: 4,
     codigo: "EAD01084",
     nome: "Cálculo II",
     cargaHoraria: 60,
     preRequisito: "Pré-Cálculo,Cálculo I",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 4,
     codigo: "EAD01088",
     nome: "Lógica e Teoria dos Conjuntos",
     cargaHoraria: 60,
     preRequisito: "Geometria Plana,Português Instrumental I",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 4,
     codigo: "EAD01089",
     nome: "Álgebra Linear I",
     cargaHoraria: 60,
     preRequisito: "Geometria Analítica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 4,
     codigo: "EAD01007",
     nome: "Construções Geométricas",
     cargaHoraria: 60,
     preRequisito: "Geometria Plana",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 4,
     codigo: "EAD00203",
     nome: "Fundamentos da Educação III",
     cargaHoraria: 60,
     preRequisito: "Fundamentos da Educação II",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 5º Período
  { 
     periodo: 5,
     codigo: "EAD01085",
     nome: "Cálculo III",
     cargaHoraria: 60,
     preRequisito: "Pré-Cálculo,Cálculo I,Cálculo II,Geometria Analítica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 5,
     codigo: "EAD01090",
     nome: "Álgebra Linear II",
     cargaHoraria: 60,
     preRequisito: "Álgebra Linear I",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 5,
     codigo: "EAD01091",
     nome: "Teoria dos Números e Álgebra",
     cargaHoraria: 60,
     preRequisito: "Lógica e Teoria dos Conjuntos",
     universidade: "UNIRIO",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 5,
     codigo: "EAD01020",
     nome: "Informática no Ensino da Matemática",
     cargaHoraria: 75,
     preRequisito: "Introdução à Informática,Geometria Analítica",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 5,
     codigo: "EAD01092",
     nome: "Educação Matemática e Geometria",
     cargaHoraria: 75,
     preRequisito: "Construções Geométricas,Geometria Espacial",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 6º Período
  { 
     periodo: 6,
     codigo: "EAD01093",
     nome: "Introdução à Combinatória de Contagem",
     cargaHoraria: 60,
     preRequisito: "Lógica e Teoria dos Conjuntos",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 6,
     codigo: "EAD01094",
     nome: "Polinômios e Números Complexos",
     cargaHoraria: 60,
     preRequisito: "Teoria dos Números e Álgebra",
     universidade: "UNIRIO",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 6,
     codigo: "EAD01095",
     nome: "Curvas e Superfícies",
     cargaHoraria: 60,
     preRequisito: "Cálculo III",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 6,
     codigo: "EAD00012",
     nome: "Prática de Ensino II - Currículo",
     cargaHoraria: 60,
     preRequisito: "Prática de Ensino I - Didática",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 6,
     codigo: "EAD01096",
     nome: "Tendências em Educação Matemática",
     cargaHoraria: 60,
     preRequisito: "Cálculo I,Fundamentos da Educação II",
     universidade: "UFF",
     selecionado: false,
     tipo: "Optativa Pedagógica",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 7º Período
  { 
     periodo: 7,
     codigo: "EAD01097",
     nome: "Estatística para Educação Básica",
     cargaHoraria: 75,
     preRequisito: "Introdução à Combinatória de Contagem",
     universidade: "UFF",
     tipo: "Optativa Matemática",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,        
  },
  { 
     periodo: 7,
     codigo: "EAD01098",
     nome: "Educação Matemática e Aritmética e Álgebra",
     cargaHoraria: 75,
     preRequisito: "Cálculo I,Teoria dos Números e Álgebra",
     universidade: "UFF",
     selecionado: false,
     tipo: "Obrigatória",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 7,
     codigo: "EAD04001",
     nome: "Introdução às Ciências Físicas I",
     cargaHoraria: 60,
     preRequisito: "Cálculo I",
     universidade: "UFRJ",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 7,
     codigo: "EAD00004",
     nome: "Fundamentos da Educação IV",
     cargaHoraria: 60,
     preRequisito: "Fundamentos da Educação III",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G2",
     diaDaSemana: "domingo",
     horario: "tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 7,
     codigo: "EAD00021",
     nome: "Estágio Supervisionado I",
     cargaHoraria: 60,
     preRequisito: "Prática de Ensino II - Currículo",
     universidade: "UFF",
     selecionado: false,
     tipo: "Obrigatória",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,   
  },

  // 8º Período
  { 
     periodo: 8,
     codigo: "EAD01099",
     nome: "Fundamentos de Análise Real",
     cargaHoraria: 60,
     preRequisito: "Cálculo I,Teoria dos Números e Álgebra",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: false,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "domingo",
     horario: "manhã (9:30 até 12:00)",
     indicadorPeriodo: 0,
     habilitado: false,   
  },
  { 
     periodo: 8,
     codigo: "EAD04005",
     nome: "Introdução às Ciências Físicas II",
     cargaHoraria: 60,
     preRequisito: "Introdução às Ciências Físicas I",
     universidade: "UFRJ",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo: "G1",
     diaDaSemana: "sábado",
     horario: "manhã (9:30 até 12:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 8,
     codigo: "EAD00022",
     nome: "Estágio Supervisionado II",
     cargaHoraria: 90,
     preRequisito: "Estágio Supervisionado I,Educação Matemática e Geometria",
     universidade: "UFF",
     selecionado: false,
     tipo: "Obrigatória",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,   
  },
  { 
     periodo: 8,
     codigo: "EAD00013",
     nome: "Prática de Ensino III - Avaliação em Educação",
     cargaHoraria: 60,
     preRequisito: "Prática de Ensino II - Currículo",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 8,
     codigo: "EAD01068",
     nome: "Atividades Complementares II",
     cargaHoraria: 60,
     preRequisito: "não tem",
     selecionado: false,
     universidade: "UFF/UNIRIO",
     tipo: "Atividade Complementar",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,   
  },
  { 
     periodo: 8,
     codigo: "EAD01100",
     nome: "Laboratório de Projetos de Ensino de Matemática I",
     cargaHoraria: 60,
     preRequisito: "Informática no Ensino da Matemática,Educação Matemática e Geometria,Educação Matemática e Aritmética e Álgebra,Introdução à Combinatória de Contagem",
     universidade: "UFF/UNIRIO",
     tipo: "Obrigatória",
     selecionado: false,
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,  
  },

  // 9º Período
  { 
     periodo: 9,
     codigo: "EAD01069",
     nome: "História da Matemática",
     cargaHoraria: 60,
     preRequisito: "Cálculo I,Teoria dos Números e Álgebra",
     universidade: "UFF",
     tipo: "Optativa Matemática",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)" ,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  {
      periodo: 9,
      codigo: "EAD04009",
      nome: "Física I a",
      cargaHoraria: 60,
      preRequisito: "Introdução às Ciências Físicas II",
      universidade: "UFF",
      tipo: "Optativa Matemática",
      provaPresencial: true,
      selecionado: false,
      grupo:"G1",
      diaDaSemana:"sábado",
      horario:"manhã (9:30 até 12:00)" ,
      indicadorPeriodo: 0,
      habilitado: false, 
  },
  { 
     periodo: 9,
     codigo: "EAD01055",
     nome: "Probabilidade e Estatística",
     cargaHoraria: 60,
     preRequisito: "Introdução à Combinatória de Contagem",
     universidade: "UFF",
     tipo: "Optativa Matemática",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"sábado",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 9,
     codigo: "EAD01028",
     nome: "Equações Diferenciais",
     cargaHoraria: 60,
     preRequisito: "Cálculo III,Álgebra Linear II",
     universidade: "UFF",
     tipo: "Optativa Matemática",
     provaPresencial: true,
     selecionado: false,
     grupo:"G2",
     diaDaSemana:"sábado",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,   
  },
  { 
     periodo: 9,
     codigo: "EAD01048",
     nome: "Introdução a Funções Complexas I",
     cargaHoraria: 60,
     preRequisito: "Cálculo II",
     universidade: "UNIRIO",
     tipo: "Optativa Matemática",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,    
  },
  { 
     periodo: 9,
     codigo: "EAD00023",
     nome: "Estágio Supervisionado III",
     cargaHoraria: 120,
     preRequisito: "Estágio Supervisionado II",
     universidade: "UFF",
     selecionado: false,
     tipo: "Obrigatória",
     provaPresencial: false,
       indicadorPeriodo: 0,
       habilitado: false   
  },
  { 
     periodo: 9,
     codigo: "EAD03017",
     nome: "Fundamentos de Educação de Jovens e Adultos",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UERJ",
     tipo: "Optativa Pedagógica",
     provaPresencial: true,
     selecionado: false,
     grupo:"G2",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false    
  },
  { 
     periodo: 9,
     codigo: "EAD01070",
     nome: "Atividades Complementares III",
     cargaHoraria: 60,
     preRequisito: "não tem",
     selecionado: false,
     universidade: "UFF/UNIRIO",
     tipo: "Atividade Complementar",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
      periodo: 9,
      codigo: "EAD01101",
      nome: "Laboratório de Projetos de Ensino de Matemática II",
      cargaHoraria: 40,
      preRequisito: "Laboratório de Projetos de Ensino de Matemática I",
      universidade: "UFF/UNIRIO",
      selecionado: false,
      tipo: "Obrigatória",
      provaPresencial: false,
      indicadorPeriodo: 0,
      habilitado: false   
  },
    { 
     periodo: 9,
     codigo: "EAD03025",
     nome: "Movimentos Sociais e Educação",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UERJ",
     tipo: "Optativa Pedagógica",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"sábado",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false    
  },

  // 10º Período
    { 
     periodo: 10,
     codigo: "EAD03003",
     nome: "Educação Especial",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Obrigatória",
     provaPresencial: true,
     selecionado: false,
     grupo:"G1",
     diaDaSemana:"sábado",
     horario:"tarde (13:30 até 16:00)",
       indicadorPeriodo: 0,
       habilitado: false   
  },
  { 
     periodo: 10,
     codigo: "EAD00032",
     nome: "Libras",
     cargaHoraria: 30,
     preRequisito: "não tem",
     universidade: "UFF",
     tipo: "Optativa Pedagógica",
     provaPresencial: true,
     selecionado: false,
     grupo:"G2",
     diaDaSemana:"domingo",
     horario:"tarde (13:30 até 16:00)",
       indicadorPeriodo: 0,
       habilitado: false   
  },
    {
      periodo: 10,
      codigo: "EAD04010",
      nome: "Física I b",
      cargaHoraria: 60,
      preRequisito: "Física I a",
      universidade: "UFF",
      tipo: "Optativa Matemática",
      provaPresencial: true,
      selecionado: false,
      grupo:"G1",
      diaDaSemana:"sábado",
      horario:"manhã (9:30 até 12:00)",
      indicadorPeriodo: 0,
      habilitado: false, 
  },
  { 
     periodo: 10,
     codigo: "EAD03033",
     nome: "Políticas Públicas em Educação",
     cargaHoraria: 60,
     preRequisito: "não tem",
     universidade: "UERJ",
     tipo: "Optativa Pedagógica",
     provaPresencial: true,
     selecionado: false,
     grupo:"G2",
     diaDaSemana:"sábado",
     horario:"tarde (13:30 até 16:00)",
     indicadorPeriodo: 0,
     habilitado: false,  
  },
  { 
     periodo: 10,
     codigo: "EAD01071",
     nome: "Atividades Complementares IV",
     cargaHoraria: 60,
     preRequisito: "não tem",
     selecionado: false,
     universidade: "UFF/UNIRIO",
     tipo: "Atividade Complementar",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,   
  },
  { 
     periodo: 10,
     codigo: "EAD00024",
     nome: "Estágio Supervisionado IV",
     cargaHoraria: 120,
     preRequisito: "Estágio Supervisionado III",
     universidade: "UFF",
     selecionado: false,
     tipo: "Obrigatória",
     provaPresencial: false,
     indicadorPeriodo: 0,
     habilitado: false,  
   },
   { 
      periodo: 10,
      codigo: "EAD01086",
      nome: "Cálculo IV",
      cargaHoraria: 60,
      preRequisito: "Cálculo III",
      universidade: "UFF",
      selecionado: false,
      grupo:"G2",
      diaDaSemana:"sábado",
      horario:"manhã (9:30 até 12:00)",
      tipo: "Optativa Matemática",
      provaPresencial: false,
      indicadorPeriodo: 0,
      habilitado: false,  
   },
   { 
       periodo: 10,
       codigo: "EAD00040",
       nome: "Tópicos Sobre a Diversidade na Educação",
       cargaHoraria: 60,
       preRequisito: "não tem",
       universidade: "UFF",
       selecionado: false,
       grupo:"G2",
       diaDaSemana:"sábado",
       horario:"manhã (9:30 até 12:00)",
       tipo: "Optativa Pedagógica",
       provaPresencial: false,
       indicadorPeriodo: 0,
       habilitado: false,  
    },
];
